name: abbys
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  tweetnacl: ^0.3.2
  path_provider: ^1.6.18
  flutter_archive: ^1.0.2
  googleapis: ^0.55.0
  google_sign_in: ^4.5.4
  loading: 1.0.2
  crypto: 2.1.5
  image_picker: ^0.6.7+12
  image_gallery_saver: '^1.6.0'
  fluttertoast: ^7.1.1
  clipboard_manager: ^0.0.4
  rxdart: ^0.24.1

dev_dependencies:
  # https://medium.com/flutterdevs/google-sign-in-with-flutter-8960580dec96
  # keytool -list -v -alias androiddebugkey -keystore debuger.keystore
  # pub global activate rename
  # pub global run rename --bundleId com.example.android.app --target android
  # pub global run rename --appname "Network Upp"
  rename: ^1.2.0
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/image/logo.png


flutter_icons:
  image_path: 'assets/image/logo.png'
  android: true
